#pragma once

#include "common.h"

enum {
    STADIA_BUTTON_UP,
    STADIA_BUTTON_DOWN,
    STADIA_BUTTON_LEFT,
    STADIA_BUTTON_RIGHT,

    STADIA_BUTTON_STADIA,
    STADIA_BUTTON_MENU,
    STADIA_BUTTON_OPTIONS,
    STADIA_BUTTON_CAPTURE,
    STADIA_BUTTON_ASSISTANT,

    STADIA_BUTTON_R3,
    STADIA_BUTTON_L3,

    STADIA_BUTTON_X,
    STADIA_BUTTON_B,
    STADIA_BUTTON_A,
    STADIA_BUTTON_Y,

    STADIA_TRIGGER_L2,
    STADIA_TRIGGER_R2,
    STADIA_TRIGGER_L1,
    STADIA_TRIGGER_R1,
};

typedef struct {

} StadiaConfiguration;
